# Generated by Django 4.2.7 on 2025-10-14 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(default='light', max_length=20)),
                ('shop_logo', models.ImageField(blank=True, null=True, upload_to='shop_logos/')),
                ('business_category', models.CharField(blank=True, max_length=60, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('map_lat', models.FloatField(blank=True, null=True)),
                ('map_lng', models.FloatField(blank=True, null=True)),
                ('staff_permissions', models.JSONField(blank=True, default=dict)),
                ('free_business_card_banner', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_settings', to='core.shop')),
            ],
        ),
    ]
