# Generated by Django 5.2.8 on 2026-01-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_otpcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otpcode',
            options={},
        ),
        migrations.RemoveField(
            model_name='otpcode',
            name='phone',
        ),
        migrations.AddField(
            model_name='otpcode',
            name='email',
            field=models.EmailField(default='no-reply@example.com', max_length=255),
            preserve_default=False,
        ),
    ]
