# Generated by Django 5.1 on 2025-11-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_businesssettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='shop_banners/'),
        ),
    ]
