# Generated by Django 5.2.8 on 2025-11-28 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_businesssettings_bank_account_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
