# Generated by Django 5.2.8 on 2025-12-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='banner',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='logo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
