# Generated by Django 5.2.8 on 2025-12-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_shop_banner_alter_shop_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesssettings',
            name='shop_logo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
