# Generated by Django 4.2.7 on 2025-10-14 20:53

from django.db import migrations, models
import shop.models.expense_models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_expense_options_expense_date_expense_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=shop.models.expense_models.current_date),
        ),
    ]
