# Generated by Django 4.2.7 on 2025-10-28 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_salereturn_purchasereturn'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_type',
            field=models.CharField(default='CASH', max_length=20),
        ),
    ]
