# Generated by Django 5.2.8 on 2025-11-28 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_orderrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show_on_website',
            field=models.BooleanField(default=True),
        ),
    ]
