# Generated by Django 5.2.8 on 2026-01-20 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_remove_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_purchase', to='shop.invoice'),
        ),
    ]
